# Generated by Django 2.0.3 on 2018-06-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MvSearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='genre',
            field=models.CharField(max_length=200),
        ),
    ]
