# Generated by Django 2.0.3 on 2018-06-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MvSearch', '0002_auto_20180601_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='imdb_score',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='popularity99',
            field=models.CharField(max_length=10),
        ),
    ]
